version: 1

update_configs:
  - package_manager: "java:maven"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: org.revapi:revapi-maven-plugin
          version_requirement: "< 0.11.4"
      - match:
          dependency_name: org.revapi:revapi-java
          version_requirement: "< 0.20.2"
      - match:
          dependency_name: org.ow2.asm:asm
